import { Dimensions, StyleSheet } from "react-native"

const screenHeight = Dimensions.get("window").height

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAFC",
    padding: 24,
    paddingTop: 60
  },
  appTitle: {
    fontSize: 36,
    fontWeight: "800",
    textAlign: "center",
    color: "#008080",
    marginBottom: 22,
    letterSpacing: -0.5,
  },
  appSubtitle: {
    textAlign: "center",
    color: "#64748B",
    fontSize: 16,
    marginBottom: 24,
    fontWeight: "500",
  },
  optionInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    paddingHorizontal: 10,
    elevation: 2,
  },
  scrollContainer: {
    position: 'relative',
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    elevation: 2,
  },
  scrollIndicator: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingVertical: 8,
    backgroundColor: 'rgba(248, 250, 252, 0.9)',
    alignItems: 'center',
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
  },
  scrollIndicatorText: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '600',
  },
  optionInput: {
    flex: 1,
    borderWidth: 0,
    paddingVertical: 12,
    paddingHorizontal: 12,
    fontSize: 16,
    color: "#1E293B",
  },
  optionsSection: {
    marginTop: 4,
  },
  optionsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  headerButtons: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  sectionTitle: {
    fontWeight: "700",
    fontSize: 18,
    color: "#1E293B",
  },
  optionsList: {
    maxHeight: screenHeight * 0.2,
    marginTop: 1,
  },
  optionText: {
    fontSize: 16,
    color: "#008080",
    fontWeight: "500",
  },
  emptyOptionsText: {
    textAlign: "center",
    color: "#64748B",
    paddingVertical: 32,
    fontSize: 16,
    fontWeight: "500",
  },
  wheelContainer: {
    alignItems: "center",
    marginTop: 24,
  },
  lottieBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  fullScreenLottie: {
    width: '100%',
    height: '100%',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
    zIndex: 2,
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: 24,
    padding: 28,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
    width: '90%',
    maxWidth: 400,
  },
  modalTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#1E293B',
    marginBottom: 4,
    letterSpacing: -0.5,
  },
  modalResultText: {
    fontSize: 32,
    fontWeight: '800',
    color: '#ff7f50',
    marginVertical: 24,
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  modalButton: {
    borderRadius: 12,
    backgroundColor: "#008080",
    paddingVertical: 6,
    width: '100%',
    marginTop: 20,
  },
  modalButtonLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: "#FFFFFF",
  },
  modalButtonContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    marginTop: 20,
    gap: 12,
  },
  modalButtonResponsive: {
    flex: 1,
    minWidth: 120,
    borderRadius: 12,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  modalScrollView: {
    flex: 1,
    width: '100%',
    padding: 16,
  },
  truthDareButtons: {
    alignItems: 'center',
    marginBottom: 24,
  },
})